SELECT TO_CHAR(dt, 'DAY') AS weekday, COUNT(*)
FROM (
  SELECT TO_DATE(EXTRACT(YEAR FROM CURRENT_DATE) || '-01-01', 'YYYY-MM-DD') + id - 1
  FROM T500
) T (dt)
WHERE EXTRACT(YEAR FROM dt) = EXTRACT(YEAR FROM CURRENT_DATE)
GROUP BY weekday

