WITH RECURSIVE cal (dy) AS (
    SELECT DATE_TRUNC('MONTH', CURRENT_TIMESTAMP)
  UNION ALL
    SELECT dy + '1 day'
    FROM cal
    WHERE EXTRACT(MONTH FROM dy) = EXTRACT(MONTH FROM dy + '1 day')
)
SELECT 
  MAX(CASE WHEN EXTRACT(ISODOW FROM dy) = 1 THEN TO_CHAR(dy, 'DD') END) AS Mo,
  MAX(CASE WHEN EXTRACT(ISODOW FROM dy) = 2 THEN TO_CHAR(dy, 'DD') END) AS Tu,
  MAX(CASE WHEN EXTRACT(ISODOW FROM dy) = 3 THEN TO_CHAR(dy, 'DD') END) AS We,
  MAX(CASE WHEN EXTRACT(ISODOW FROM dy) = 4 THEN TO_CHAR(dy, 'DD') END) AS Th,
  MAX(CASE WHEN EXTRACT(ISODOW FROM dy) = 5 THEN TO_CHAR(dy, 'DD') END) AS Fr,
  MAX(CASE WHEN EXTRACT(ISODOW FROM dy) = 6 THEN TO_CHAR(dy, 'DD') END) AS Sa,
  MAX(CASE WHEN EXTRACT(ISODOW FROM dy) = 7 THEN TO_CHAR(dy, 'DD') END) AS Su
FROM cal
GROUP BY EXTRACT(WEEK FROM dy)
ORDER BY MIN(dy)
