-- Oracle
WITH T (strings) AS (
            SELECT '1010 switch' FROM DUAL
  UNION ALL SELECT '333' FROM DUAL
  UNION ALL SELECT '3453430278' FROM DUAL
  UNION ALL SELECT 'ClassSummary' FROM DUAL
  UNION ALL SELECT 'findRow 55' FROM DUAL
  UNION ALL SELECT 'threes' FROM DUAL
)
SELECT *
FROM T
WHERE REGEXP_COUNT(strings, '[a-zA-Z]') > 0
AND REGEXP_COUNT(strings, '[0-9]') > 0
