-- Oracle
/**
CREATE TABLE IT_RESEARCH (deptno NUMBER, ename VARCHAR2(20));
CREATE TABLE IT_APPS (deptno NUMBER, ename VARCHAR2(20));
INSERT INTO IT_RESEARCH VALUES (100,'HOPKINS');
INSERT INTO IT_RESEARCH VALUES (100,'JONES');
INSERT INTO IT_RESEARCH VALUES (100,'TONEY');
INSERT INTO IT_RESEARCH VALUES (200,'MORALES');
INSERT INTO IT_RESEARCH VALUES (200,'P.WHITAKER');
INSERT INTO IT_RESEARCH VALUES (200,'MARCIANO');
INSERT INTO IT_RESEARCH VALUES (200,'ROBINSON');
INSERT INTO IT_RESEARCH VALUES (300,'LACY');
INSERT INTO IT_RESEARCH VALUES (300,'WRIGHT');
INSERT INTO IT_RESEARCH VALUES (300,'J.TAYLOR');
INSERT INTO IT_APPS VALUES (400,'CORRALES');
INSERT INTO IT_APPS VALUES (400,'MAYWEATHER');
INSERT INTO IT_APPS VALUES (400,'CASTILLO');
INSERT INTO IT_APPS VALUES (400,'MARQUEZ');
INSERT INTO IT_APPS VALUES (400,'MOSLEY');
INSERT INTO IT_APPS VALUES (500,'GATTI');
INSERT INTO IT_APPS VALUES (500,'CALZAGHE');
INSERT INTO IT_APPS VALUES (600,'LAMOTTA');
INSERT INTO IT_APPS VALUES (600,'HAGLER');
INSERT INTO IT_APPS VALUES (600,'HEARNS');
INSERT INTO IT_APPS VALUES (600,'FRAZIER');
INSERT INTO IT_APPS VALUES (700,'GUINN');
INSERT INTO IT_APPS VALUES (700,'JUDAH');
INSERT INTO IT_APPS VALUES (700,'MARGARITO');
**/

WITH
A (grp, deptno, ename, type) AS (
            SELECT 1, deptno, '  ' || ename, 1 FROM it_research
  UNION ALL SELECT 2, deptno, '  ' || ename, 1 FROM it_apps
  UNION ALL SELECT 1, deptno, MAX(deptno) || '', 0 FROM it_research GROUP BY deptno
  UNION ALL SELECT 2, deptno, MAX(deptno) || '', 0 FROM it_apps     GROUP BY deptno
),
B AS (
  SELECT grp, deptno, ename AS ename, RANK() OVER (PARTITION BY grp ORDER BY deptno, type, ename) AS rn
  FROM A
)
SELECT 
  MAX(CASE WHEN grp = 1 THEN ename END) research,
  MAX(CASE WHEN grp = 2 THEN ename END) apps
FROM B
GROUP BY rn
ORDER BY rn

